name: template_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  riverpod_annotation: ^2.1.1
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  go_router: ^7.1.1
  intl: ^0.18.1
  uuid: ^3.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
